### ISSUE TITLE
cirq 0.5.0 amplitudes simulator

### ISSUE THREAD

**Issue by alexandrupaler** [ngnrsaa/qflex#122]
once 0.6.0 is out remove the` cirq_amplitudes_sim.py` from` python/cirq_interface`, because 0.6.0 has the support for `SimulatesAmplitudes` class

**Comment by 95-martin-orion** [comment]
[Cirq v0.6.0](https://github.com/quantumlib/Cirq/releases/tag/v0.6.0) has been released, unblocking this issue. @alexandrupaler, please get in touch if it looks like the new Cirq version is breaking our tests.
