### ISSUE TITLE
does pytest close and remove mkstemp file handles?

### ISSUE THREAD

**Issue by alexandrupaler** [ngnrsaa/qflex#132]
The `simulation_test.py` script uses temporary files. 
https://github.com/ngnrsaa/qflex/blob/c7038b0e06d2f9312a3b5db41dcd9a244f276220/tests/python/simulation_test.py#L268

The documentation of [mkstemp](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) mentions that the user is responsible for removing the files. The handles are not removed with something like below
```
os.close(fd)
os.unlink(path)
```

Is this intended behaviour?

**Comment by kkissell** [comment]
This is fixed in the patch I uploaded in #289.  mkstemp isn't optimal for this use case.
