### ISSUE TITLE
standardise input between qflex and ShallowQC

### ISSUE THREAD

**Issue by dlyongemallo** [ngnrsaa/qflex#18]
qflex has a variable `num_qubits` which is read in as the first line of an input file, and is assumed to be the number of qubits in a rectangular grid of size `I * J`. (All qubits set to `off` are ignored.)

ShallowQC also has a variable named `num_qubits`, which is also read in as the first line of an input file, but denotes the number of qubits in the circuit. Consequently, when qflex reads in a ShallowQC circuit file, it has to read the first line into a dummy variable, then calculate `num_qubits` based on `I` and `J`.

The file formats should be reconciled so that circuit files can be shared without modifications to inputs or source code.

**Comment by viathor** [comment]
ShallowQC has indeed been discontinued. I think it makes sense to defer the convergence with qsim until it is open sourced, because qsim's format may change before that happens. I propose to close this issue.
