### ISSUE TITLE
Check continuous integration.

### ISSUE THREAD

**Issue by s-mandra** [ngnrsaa/qflex#186]

**Comment by 95-martin-orion** [comment]
Related to #7, I think? When I tried enabling Travis, this repo didn't show up as an option - I think only an owner can set it up.

@s-mandra, one note on this: Google has restrictions against using the commercial version of Travis ([travis-ci.com](https://travis-ci.com/)) since it gives Travis write permissions on the repo. The free version ([travis-ci.org](https://travis-ci.org/)) does not require this permission, so it's what we should be using.

**Comment by s-mandra** [comment]
> Related to #7, I think? When I tried enabling Travis, this repo didn't show up as an option - I think only an owner can set it up.
> 
> @s-mandra, one note on this: Google has restrictions against using the commercial version of Travis ([travis-ci.com](https://travis-ci.com/)) since it gives Travis write permissions on the repo. The free version ([travis-ci.org](https://travis-ci.org/)) does not require this permission, so it's what we should be using.

I'll take a look into this.

**Comment by s-mandra** [comment]
Looking right now and travis requires write permission for:

Commit statuses
Read and write access
This application will be able to read and write commit statuses (no direct code access).

Deployments
Manage deployments and deployment status
This application will be able to manage deployments and deployment status (no direct code access).

Repository webhooks and services
Read and write access
This application will be able to read and modify repository webhooks and services (no direct code access).

Is this ok on the Google side?

**Comment by 95-martin-orion** [comment]
> Looking right now and travis requires write permission for: {...}

This sounds correct. The Google restriction is specifically on *code* write permissions, which are excluded by the above list.

**Comment by s-mandra** [comment]
It's working :) I need to fix .travis.yml but, beside that, everything is working as expected.

**Comment by s-mandra** [comment]
@95-martin-orion, what do you think about [this](https://lgtm.com/)?

**Comment by 95-martin-orion** [comment]
Is it possible to view the results of Travis CI for a particular PR? Nothing shows up for me in the "Checks" tab (compare with e.g. [this Cirq PR](https://github.com/quantumlib/Cirq/pull/2402/checks)).

> @95-martin-orion, what do you think about [this](https://lgtm.com/)?

Google internal docs give it the OK - would this be alongside or in place of Travis CI?

**Comment by s-mandra** [comment]
> Is it possible to view the results of Travis CI for a particular PR? Nothing shows up for me in the "Checks" tab (compare with e.g. [this Cirq PR](https://github.com/quantumlib/Cirq/pull/2402/checks)).

Not sure :( I never used Travis CI and I'm learning now!
 
> > @95-martin-orion, what do you think about [this](https://lgtm.com/)?
> 
> Google internal docs give it the OK - would this be alongside or in place of Travis CI?

Great! It would be alongside.

**Comment by s-mandra** [comment]
Let me know if you have any other integration it would worth to include. Thanks!
