### ISSUE TITLE
Can't get python interface to work

### ISSUE THREAD

**Issue by kevinsung** [ngnrsaa/qflex#219]
After following the instructions for setting up Python, I try to run the example script by executing `python qflex_cirq_example.py`. I get
```
Traceback (most recent call last):
  File "qflex_cirq_example.py", line 2, in <module>
    import python.cirq_interface.qflex_simulator as qsim
  File "/usr/local/google/home/sungkevin/Projects/qflex/python/cirq_interface/qflex_simulator.py", line 5, in <module>
    from python import qflex
ImportError: cannot import name 'qflex' from 'python' (unknown location)
```

**Comment by s-mandra** [comment]
Thanks for catching this. I've created a patch to solve the problem in #221. The problem is related to the fact that it's missing the relative path to where to find the qflex python modules. Try now with:
```
python3 python/qflex_cirq_example.py
```
from the root folder of qflex (it works for me).

**Comment by alexandrupaler** [comment]
Thank you for pointing this out. It is indeed an issue with the paths. However, we have also a relative paths related issue #167 . I guess the solution should consider module __init__.py.

**Comment by kevinsung** [comment]
It still doesn't work for me.

**Comment by alexandrupaler** [comment]
Have you compiled QFlex with `make pybind`? In the Python folder there should be a file with a name like `qflex.[long_name].so`

**Comment by 95-martin-orion** [comment]
> Have you compiled QFlex with `make pybind`?

Note that this normally runs during the default `make` invocation; if it didn't, the logs should indicate what prevented it from doing so (usually missing dependencies, IIRC).

**Comment by kevinsung** [comment]
I didn't have pybind. Installing it fixed the issue. Thanks!

**Comment by alexandrupaler** [comment]
@s-mandra Should we suggest the user to run pip install -r requirements.txt if one if the python dependencies fail on configure?

**Comment by s-mandra** [comment]
Sure, I can add that to `README.md` and `docs/install.md`.
