### ISSUE TITLE
check_format.sh not catching incorrectly formatted python files. 

### ISSUE THREAD

**Issue by alankao64** [ngnrsaa/qflex#239]
Incorrectly formatted python files aren't being caught in check_format.sh, yet when manually running YAPF, they are shown as incorrectly formatted.

**Comment by alankao64** [comment]
Seems like line 72 in check_format.sh is the issue: 
`  if [[ $(${PY_CHECKER} -d "$filename" | wc -l) > 0 ]]; then`
I don't think its catching when the wordcount is over 0.

**Comment by 95-martin-orion** [comment]
It should be possible to use the error code returned by `yapf --diff <filename>` instead of checking the size of the diff. From the [YAPF docs](https://github.com/google/yapf#return-codes):

> If `--diff` is supplied, YAPF returns zero when no changes were necessary, non-zero otherwise

**Comment by alexandrupaler** [comment]
This could be due to different yapf versions? There is a system wide yapf and a local one in the venv environment?

**Comment by alankao64** [comment]
Seems to have been resolved with PR #237
