### ISSUE TITLE
libopenblas-dev

### ISSUE THREAD

**Issue by alexandrupaler** [ngnrsaa/qflex#275]
I have successfully installed openblas-dev
```
libopenblas-dev is already the newest version (0.2.20+ds-4).
```

However, the following line
```
autoreconf -i && autoconf && ./configure
```
complains about OpenBlas. I have Ubuntu 19.04.
```
configure: error: Please install OpenBLAS before configuring.
```

**Comment by 95-martin-orion** [comment]
My current version of `libopenblas-dev` is 0.3.7:
```
sudo apt-get install libopenblas-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenblas-dev is already the newest version (0.3.7+ds-1).
```

Could you try running `sudo apt-get update` and re-installing OpenBLAS?

**Comment by alexandrupaler** [comment]
unfortunately after update i receive still 0.2

În joi, 27 feb. 2020 la 11:37, Orion Martin <notifications@github.com> a
scris:

**Comment by alexandrupaler** [comment]
Problem solved: I was in a conda environment. It is strange, because the conda had the correct Blas, but configure did not find it. I exited the conda, and configure works.
