### ISSUE TITLE
evaluate_circuit.cpp compile after make clean-all

### ISSUE THREAD

**Issue by alexandrupaler** [ngnrsaa/qflex#276]
After successfully configuring the Makefiles. The compiler complains
```
evaluate_circuit.cpp: In function ‘std::vector<std::pair<std::__cxx11::basic_string<char>, std::complex<double> > > qflex::EvaluateCircuit(qflex::QflexInput*)’:
evaluate_circuit.cpp:190:37: error: unused variable ‘index’ [-Werror=unused-variable]
         for (const auto& [index, dim] : index_dim) {
                                     ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-unused-command-line-argument’ [-Werror]

```

**Comment by 95-martin-orion** [comment]
This is a [clang flag](https://clang.llvm.org/docs/DiagnosticsReference.html#wunused-command-line-argument) - what version of clang are you running? My system reports v8.0.1:
```
$ clang --version
clang version 8.0.1-3+build1 (tags/RELEASE_801/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Just to confirm, is this error happening when running `make` from the top-level qflex/ directory?

**Comment by alexandrupaler** [comment]
I should be using G++ 7.4 and not clang

În joi, 27 feb. 2020 la 12:02, Orion Martin <notifications@github.com> a
scris:

**Comment by 95-martin-orion** [comment]
As discussed offline, this can be avoided by either using the `index` variable (if it's actually needed) or iterating only over the values (`dim`s) of `index_dim`. Since we should be avoiding unused variables in any case, we should submit this fix - @alexandrupaler, would you be able to send a PR for this?

**Comment by s-mandra** [comment]
`make clean-all` should remove everything, including all the `Makefile`s. Hence I'm surprised you can even run `make` after `make clean-all`.

**Comment by alexandrupaler** [comment]
@s-mandra: #249 addressed this issue by rewriting the for loop.
